version: '3.8'

services:
  database:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Admin12345
      - ACCEPT_EULA=Y
    volumes:
      - 'db-data:/var/opt/mssql'
volumes:
  db-data:
    name: db-data
